name: lsystem
description: l-system experiments
dependencies:
  vector_math: ">=2.0.5 <3.0.0"
  build_runner: "any"
  build_web_compilers: "any"
  sprintf: "any"
  chronosgl: ">=4.1.1"
environment:
  sdk: "^3.3.4"
